---
version: 2
sources:
- name: "qa_team_prakhar"
  database: "qa_team"
  schema: "prakhar"
  tables:
  - name: "aus_team"
    config:
      tags:
      - "pipeline:pipeline1"
    columns:
    - name: "id"
      dataType:
        type: "Bigint"
    - name: "player_name"
      dataType:
        type: "String"
    - name: "total_matches"
      dataType:
        type: "Bigint"
    - name: "total_scores"
      dataType:
        type: "Bigint"
    - name: "category"
      dataType:
        type: "String"
    - name: "total_wickets"
      dataType:
        type: "Bigint"
    - name: "best_wicket_performance"
      dataType:
        type: "String"
    type: "table"
- name: "qa_team_qa_orchestration"
  database: "qa_team"
  schema: "qa_orchestration"
  tables:
  - name: "nba_games"
    config:
      tags:
      - "pipeline:pipeline1"
    columns:
    - name: "game_id"
      dataType:
        type: "String"
    - name: "season_year"
      dataType:
        type: "Bigint"
    - name: "game_date"
      dataType:
        type: "Date"
    - name: "home_team_id"
      dataType:
        type: "String"
    - name: "away_team_id"
      dataType:
        type: "String"
    - name: "home_team_score"
      dataType:
        type: "Bigint"
    - name: "away_team_score"
      dataType:
        type: "Bigint"
    - name: "overtime_periods"
      dataType:
        type: "Bigint"
    - name: "attendance"
      dataType:
        type: "Bigint"
    - name: "arena_name"
      dataType:
        type: "String"
    type: "table"
